import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/scss/styles.scss';
import Theme from '@/components/Theme/Theme';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/f51f49f955.js" crossOrigin="anonymous" />
      <body className={inter.className}>
        <Theme />
        {children}
      </body>
    </html>
  )
}
