export const SYLLABUS_KEYS = Object.freeze({
  ID: "a",
  TITLE: "b",
  TITLE_JP: "c",
  INSTRUCTOR: "d",
  INSTRUCTOR_JP: "e",
  LANG: "f",
  TYPE: "g",
  TERM: "h",
  OCCURRENCES: "i",
  MIN_YEAR: "j",
  CATEGORY: "k",
  CREDIT: "l",
  LEVEL: "m",
  EVAL: "n",
  CODE: "o",
  SUBTITLE: "p",
  SCHOOL: "q",
  OCC_DAY: "d",
  OCC_PERIOD: "p",
  OCC_LOCATION: "l",
  EVAL_TYPE: "t",
  EVAL_PERCENT: "p",
  EVAL_CRITERIA: "c",
});
