import React from 'react';
import { connect } from 'react-redux';

import {
  fetchBldgClassrooms,
  fetchBldgOccupiedClassrooms
} from '../actions/index';
import ClassroomList from '../components/ClassroomList';
import PropTypes from 'prop-types';

class ClassroomListContainer extends React.Component {
  componentDidMount() {
    this.props.fetchBldgClassrooms(this.props.match.params.bldgName);
    this.props.fetchBldgOccupiedClassrooms(this.props.match.params.bldgName);
  }

  render() {
    return <div />;
  }
}

const getClassroomNames = (classroomIds, classroomsById) => {
  if (classroomIds.length !== 0) {
    const classroomNames = classroomIds.map(id => classroomsById[id]['name']);
    console.log(classroomNames);
    return classroomNames;
  }
  return [];
};

const getOccupiedClassrooms = (classroomIds, classroomsById) => {
  if (classroomIds.length !== 0) {
    const classrooms = classroomIds.map(id => {
      return {
        name: classroomsById[id]['name'],
        course: classroomsById[id]['courses']
      };
    });
    console.log(classrooms);
    return classrooms;
  }
  return [];
};

const mapStateToProps = (state, ownProps) => {
  return {
    classrooms: getClassroomNames(
      state.bldgClassroomIds,
      state.bldgClassroomsById
    ),
    occupiedClassrooms: getOccupiedClassrooms(
      state.bldgOccupiedClassroomIds,
      state.bldgOccupiedClassroomsById
    )
  };
};

//using shorthand syntax
const mapDispatchToProps = {
  fetchBldgClassrooms,
  fetchBldgOccupiedClassrooms
};

//export a container component generated by react-redux
export default connect(mapStateToProps, mapDispatchToProps)(
  ClassroomListContainer
);
