import React from 'react';
import { connect } from 'react-redux';

import { fetchNishiBldgs } from '../actions/index';
import BuildingList from '../components/BuildingList';
import PropTypes from 'prop-types';

class NishiBuildingList extends React.Component {
  constructor(props) {
    super(props);
    this.name = 'Nishi-Waseda Campus Buildings';
  }

  componentDidMount() {
    this.props.fetchNishiBldgs();
  }

  render() {
    return <BuildingList name={this.name} bldgNames={this.props.bldgNames} />;
  }
}

const getBldgNames = (nishiBldgIds, nishiBldgsById) => {
  if (nishiBldgIds.length !== 0) {
    return nishiBldgIds.map(id => nishiBldgsById[id]['name']);
  }
  return [];
};

const mapStateToProps = (state, ownProps) => {
  return {
    bldgNames: getBldgNames(state.nishiBldgIds, state.nishiBldgsById)
  };
};

//shorthand syntax
const mapDispatchToProps = {
  fetchNishiBldgs
};

//export a container component generated by react-redux
export default connect(mapStateToProps, mapDispatchToProps)(NishiBuildingList);
