import * as Schools from "@bit/wasedatime.syllabus.ts.constants.schools";

export const schoolCodeMap: Readonly<{ [k: string]: string }> = {
  "11": Schools.PSE,
  "12": Schools.LAW,
  "15": Schools.EDU,
  "16": Schools.SOC,
  "18": Schools.SSS,
  "19": Schools.HUM,
  "20": Schools.SPS,
  "21": Schools.SILS,
  "23": Schools.CMS,
  "24": Schools.HSS,
  "26": Schools.FSE,
  "27": Schools.CSE,
  "28": Schools.ASE,
  "31": Schools.G_PS,
  "32": Schools.G_E,
  "33": Schools.G_LAW,
  "34": Schools.G_LAS,
  "37": Schools.G_EDU,
  "38": Schools.G_HUM,
  "39": Schools.G_SSS,
  "40": Schools.G_SAPS,
  "42": Schools.G_ITS,
  "43": Schools.G_SJAL,
  "44": Schools.G_IPS,
  "47": Schools.G_WLS,
  "48": Schools.G_SA,
  "50": Schools.G_SPS,
  "51": Schools.G_FSE,
  "52": Schools.G_CSE,
  "53": Schools.G_ASE,
  "54": Schools.G_SEEE,
  "56": Schools.G_SICCS,
  "57": Schools.G_WBS,
  "71": Schools.ART,
  "92": Schools.CJL,
  "98": Schools.CIE,
  "9S": Schools.GEC,
};

export default schoolCodeMap;
