export enum SyllabusKey {
  ID = "a",
  TITLE = "b",
  TITLE_JP = "c",
  INSTRUCTOR = "d",
  INSTRUCTOR_JP = "e",
  LANG = "f",
  TYPE = "g",
  TERM = "h",
  OCCURRENCES = "i",
  MIN_YEAR = "j",
  CATEGORY = "k",
  CATEGORY_JP = "q",
  CREDIT = "l",
  LEVEL = "m",
  EVAL = "n",
  CODE = "o",
  SUBTITLE = "p",
  SCHOOL = "r",
  OCC_DAY = "d",
  OCC_PERIOD = "p",
  OCC_LOCATION = "l",
  EVAL_TYPE = "t",
  EVAL_PERCENT = "p",
  EVAL_CRITERIA = "c"
}

export enum School {
  SILS = "SILS",
  PSE = "PSE",
  SSS = "SSS",
  FSE = "FSE",
  ASE = "ASE",
  CSE = "CSE",
  LAW = "LAW",
  CMS = "CMS",
  HSS = "HSS",
  EDU = "EDU",
  SOC = "SOC",
  HUM = "HUM",
  SPS = "SPS",
  G_ASE = "G_ASE",
  G_CSE = "G_CSE",
  G_EDU = "G_EDU",
  G_FSE = "G_FSE",
  G_SAPS = "G_SAPS",
  G_ITS = "G_ITS",
  G_SA = "G_SA",
  G_SC = "G_SC",
  G_E = "G_E",
  G_SJAL = "G_SJAL",
  G_SICCS = "G_SICCS",
  G_PS = "G_PS",
  G_SSS = "G_SSS",
  G_HUM = "G_HUM",
  G_IPS = "G_IPS",
  G_LAS = "G_LAS",
  G_LAW = "G_LAW",
  G_SPS = "G_SPS",
  G_WBS = "G_WBS",
  G_WLS = "G_WLS",
  G_SEEE = "G_SEEE",
  ART = "ART",
  CJL = "CJL",
  CIE = "CIE",
  GEC = "GEC"
}

export enum Term {
  SPRING_SEM = "0s",
  SPRING_QUART = "0q",
  SUMMER_QUART = "1q",
  FULL_YEAR = "f",
  INTENSIVE_SPRING_SEM = "0si",
  INTENSIVE_SPRING_FALL_SEM = "0si&2si",
  INTENSIVE_SPRING = "0i",
  INTENSIVE_SUMMER = "1i",
  SPRING_SUMMER = "0&1",
  FALL_SEM = "2s",
  FALL_QUART = "2q",
  WINTER_QUART = "3q",
  INTENSIVE_FALL_SEM = "2si",
  INTENSIVE_FALL = "2i",
  INTENSIVE_WINTER = "3i",
  FALL_WINTER = "2&3",
  UNDECIDED = "undecided"
}