export const FETCH_STATS_REQUEST = "FETCH_STATS_REQUEST";
export const FETCH_STATS_SUCCESS = "FETCH_STATS_SUCCESS";
export const FETCH_STATS_FAILURE = "FETCH_STATS_FAILURE";
export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";
export const FETCH_BUILDINGS_REQUEST = "FETCH_BUILDINGS_REQUEST";
export const FETCH_BUILDINGS_SUCCESS = "FETCH_BUILDINGS_SUCCESS";
export const FETCH_BUILDINGS_FAILURE = "FETCH_BUILDINGS_FAILURE";
export const FETCH_BLDG_CURRENT_CLASSROOMS = "FETCH_BLDG_CURRENT_CLASSROOMS";
export const HYDRATE_ADDED_COURSES = "HYDRATE_ADDED_COURSES";
export const ADD_COURSE = "ADD_COURSE";
export const REMOVE_COURSE = "REMOVE_COURSE";
export const CHANGE_COURSE_COLOR = "CHANGE_COURSE_COLOR";
export const TOGGLE_COURSE_VISIBILITY = "TOGGLE_COURSE_VISIBILITY";
export const CHANGE_COURSES_SORTING_OPTION = "CHANGE_COURSES_SORTING_OPTION";
export const CHANGE_USER_DISPLAY_LANG = "CHANGE_USER_DISPLAY_LANG";
export const SET_FIRST_TIME_ACCESS_TO_FALSE = "SET_FIRST_TIME_ACCESS_TO_FALSE";
export const ADD_SCHOOL = "ADD_SCHOOL";
export const ADD_SCHOOL_FETCH_COURSES_REQUEST =
  "ADD_SCHOOL_FETCH_COURSES_REQUEST";
export const ADD_SCHOOL_FETCH_COURSES_SUCCESS =
  "ADD_SCHOOL_FETCH_COURSES_SUCCESS";
export const ADD_SCHOOL_FETCH_COURSES_FAILURE =
  "ADD_SCHOOL_FETCH_COURSES_FAILURE";
export const REMOVE_SCHOOL = "REMOVE_SCHOOL";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
