/*
 * action types
 */

export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';
export const SEARCH_COURSES = 'SEARCH_COURSES';
export const FETCH_COURSE_BY_ID = 'FETCH_COURSE_BY_ID';
export const FETCH_NISHI_BLDGS = 'FETCH_NISHI_BLDGS';
export const FETCH_BLDG_CURRENT_CLASSROOMS = 'FETCH_BLDG_CURRENT_CLASSROOMS';
