/*
 * action types
 */

export const FETCH_NISHI_BLDGS = 'FETCH_NISHI_BLDGS';
export const FETCH_BLDG_CLASSROOMS = 'FETCH_BLDG_CLASSROOMS';
export const FETCH_BLDG_OCCUPIED_CLASSROOMS = 'FETCH_BLDG_OCCUPIED_CLASSROOMS';
export const FETCH_BLDG_CURRENT_CLASSROOMS = 'FETCH_BLDG_CURRENT_CLASSROOMS';
