/*
 * action types
 */

export const SEARCH_COURSES = 'SEARCH_COURSES';
export const FETCH_COURSE_BY_ID = 'FETCH_COURSE_BY_ID';
export const FETCH_NISHI_BLDGS = 'FETCH_NISHI_BLDGS';
export const FETCH_BLDG_CURRENT_CLASSROOMS = 'FETCH_BLDG_CURRENT_CLASSROOMS';
