import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import fs from "fs";
import path from "path";
import FeedLink from '../components/feedLink';

interface HomeProps {
  feedNames: string[]
}

const Home: NextPage = ({ feedNames }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          feedNames.map(name => <FeedLink name={name} />)
        }
      </main>
    </div>
  )
}

export default Home;

export async function getServerSideProps() {
  const POSTS_DIRECTORY = path.join(process.cwd(), "public", "feeds");
  const feedNames = await fs.readdirSync(POSTS_DIRECTORY).filter(file => path.extname(file).toLowerCase() === '.md').map(name => name.replace('.md', ''));
  return { props: { feedNames } };
}
