import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import fs from "fs";
import path from "path";
import FeedLink from '../components/feedLink';
import Grid from "@material-ui/core/Grid";

interface HomeProps {
  feedNames: string[]
}

const Home: NextPage = ({ feedNames }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 style={{ color: "#555" }}>Welcome to WasedaTime Feeds!</h2>
        <hr style={{ width: "50%", color: "#555" }} />
        <div style={{ lineHeight: 1, textAlign: 'center', padding: '0px 1em 1em 1em' }}>
          <p>Here we offer you articles that may be helpful for your student life & future career.</p>
          <p>
            We are looking for more feeds that support student life!
            Please contant us if you (as a student or organization) are interested:{' '}
            <a href="mailto:contact@wasedatime.com" style={{ color: '#3366ff' }}>contact@wasedatime.com</a>
          </p>
        </div>

        <Grid container spacing={4}>
          {
            feedNames.map(name => <FeedLink name={name} />)
          }
        </Grid>
      </main>
    </div>
  )
}

export default Home;

export async function getServerSideProps() {
  const POSTS_DIRECTORY = path.join(process.cwd(), "public", "feeds");
  const feedNames = await fs.readdirSync(POSTS_DIRECTORY).filter(file => path.extname(file).toLowerCase() === '.md').map(name => name.replace('.md', ''));
  return { props: { feedNames } };
}
