export default oldTermMap = {
  springSem: "0s",
  springQuart: "0q",
  summerQuart: "1q",
  fullYear: "f",
  intensiveSpringSem: "0si",
  intensiveSpringFallSem: "0si&2si",
  intensiveSpring: "0i",
  intensiveSummer: "1i",
  springSummer: "0&1",
  fallSem: "2s",
  fallQuart: "2q",
  winterQuart: "3q",
  intensiveFallSem: "2si",
  intensiveFall: "2i",
  intensiveWinter: "3i",
  fallWinter: "2&3",
  undecided: "undecided",
};
